[package]
name = "logreader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic_enum = "0.2.0"
inkbound-parser.workspace = true
log.workspace = true
notify = "6.1.1"
