[workspace]
resolver = "2"
members = [
  "main",
  "inkbound-parser",
  "parser-overlay",
]

[workspace.dependencies]
inkbound-parser = { path = "./inkbound-parser" }
log = "0.4.20"

[patch.crates-io]
egui = { git = "https://github.com/richteer/egui", branch = "eframe-overlay" }
eframe = { git = "https://github.com/richteer/egui", branch = "eframe-overlay" }