name: Release Build
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-gnu]
        include:
          - target: x86_64-pc-windows-gnu
            exe: .exe
    steps:
      - uses: actions/checkout@master

      - name: build
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.target }}
          toolchain: stable
          args: "--release --features auto_update"
          strip: true

      - name: compress
        run: "cp target/${{ matrix.target }}/release/inkbound-dps${{ matrix.exe }} . && zip inkbound-dps_${{ github.ref_name }}_${{ matrix.target }}.zip inkbound-dps${{ matrix.exe }} README.md LICENSE CHANGELOG.md"

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: "*.zip"

  release:
      runs-on: ubuntu-latest
      needs: ["build"]
      steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          args: "--current --strip header"

      - name: download
        uses: actions/download-artifact@v3

      - name: generate release
        uses: softprops/action-gh-release@v1
        with:
          files: "**/*.zip"
          body: "${{ steps.git-cliff.outputs.content }}"
